# This file is optional - docker-compose.yml uses the official mongo image
# If you need custom MongoDB configuration, you can extend it here

FROM mongo:7.0

# Add custom configuration if needed
# COPY mongo.conf /etc/mongod.conf

